In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
train=pd.read_csv('Desktop/Analytics_Vidhya/football_hackathon/train.csv')
test=pd.read_csv('Desktop/Analytics_Vidhya/football_hackathon/test.csv')
submission=pd.read_csv('Desktop/Analytics_Vidhya/football_hackathon/sample_submission.csv')

In [3]:
train.head()

,row_id,scout_id,rating_num,winner,team,competitionId,player_position_1,player_position_2,player_height,player_weight,...,team2_defensive_derived_var_10,team2_offensive_derived_var_11,team2_offensive_derived_var_12,team2_offensive_derived_var_13,team2_offensive_derived_var_14,team2_defensive_derived_var_15,team2_offensive_derived_var_16,team2_defensive_derived_var_17,team2_offensive_derived_var_18,team2_offensive_derived_var_19
0,1,13,7.0,winner,team1,8,7.0,7.0,0.317073,0.48,...,0.193658,0.131548,0.097131,0.600944,0.338892,0.347980,0.034157,0.288962,0.310727,0.204925
1,3,16,6.5,loser,team2,8,3.0,9.0,0.463415,0.42,...,0.190500,0.173697,0.272801,0.605659,0.526761,0.468976,0.054034,0.334962,0.380073,0.295392
2,4,4,8.5,loser,team1,5,11.0,11.0,0.682927,0.44,...,0.312314,0.250756,0.212631,0.558833,0.686523,0.441749,0.219441,0.414288,0.570757,0.437500
3,5,13,8.0,loser,team2,4,17.0,17.0,0.682927,0.58,...,0.282556,0.155969,0.206503,0.533002,0.373959,0.527733,0.095201,0.423040,0.330754,0.235558
4,7,11,3.5,draw,team1,5,10.0,10.0,0.731707,0.70,...,0.450453,0.199050,0.134002,0.688773,0.681724,0.733625,0.128719,0.448360,0.444946,0.312500

In [4]:
y=train['rating_num']

In [5]:
train.describe()

,row_id,scout_id,rating_num,competitionId,player_position_1,player_position_2,player_height,player_weight,player_general_var_0,player_general_var_1,...,team2_defensive_derived_var_10,team2_offensive_derived_var_11,team2_offensive_derived_var_12,team2_offensive_derived_var_13,team2_offensive_derived_var_14,team2_defensive_derived_var_15,team2_offensive_derived_var_16,team2_defensive_derived_var_17,team2_offensive_derived_var_18,team2_offensive_derived_var_19
count,20453.000000,20453.000000,20453.000000,20453.000000,20378.000000,20378.000000,20451.000000,20451.000000,20453.000000,20453.000000,...,19026.000000,20332.000000,19019.000000,19021.000000,19026.000000,19026.000000,19026.000000,19026.000000,19026.000000,19026.000000
mean,14257.557033,10.023566,6.887303,7.311837,7.609481,8.012612,0.496925,0.455471,0.029717,0.003276,...,0.350022,0.179766,0.253738,0.582760,0.480930,0.497442,0.113251,0.424523,0.420103,0.333038
std,8353.543104,5.712044,1.852367,2.345699,5.059591,4.913142,0.160769,0.140848,0.082089,0.057142,...,0.140589,0.059541,0.138928,0.150763,0.163294,0.135420,0.061303,0.098739,0.121958,0.143902
min,1.000000,1.000000,0.000000,4.000000,1.000000,1.000000,0.024390,0.040000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.046945,0.000000,0.044144,0.000000,0.000000
25%,7048.000000,3.000000,6.000000,5.000000,3.000000,3.000000,0.390244,0.340000,0.000000,0.000000,...,0.246247,0.158557,0.153925,0.485600,0.365868,0.410089,0.068929,0.357223,0.333557,0.235558
50%,14093.000000,12.000000,6.500000,7.000000,7.000000,8.000000,0.512195,0.440000,0.000000,0.000000,...,0.339490,0.184254,0.239381,0.592093,0.479270,0.499538,0.102904,0.421710,0.420148,0.320256
75%,21381.000000,15.000000,8.000000,9.000000,11.000000,11.000000,0.609756,0.540000,0.000000,0.000000,...,0.431876,0.215570,0.338749,0.691803,0.596090,0.594952,0.149055,0.489914,0.507056,0.425171
max,29227.000000,26.000000,10.000000,15.000000,23.000000,23.000000,0.975610,1.000000,1.000000,1.000000,...,0.962835,1.000000,1.000000,1.000000,0.989602,0.977524,1.000000,1.000000,1.000000,1.000000

In [6]:
train['player_weight']=train['player_weight'].fillna(train['player_weight'].median())
train['player_height']=train['player_height'].fillna(train['player_height'].median())
train['player_position_2']=train['player_position_2'].fillna(0)
train['player_position_1']=train['player_position_1'].fillna(0)

In [7]:
test['player_position_1']=test['player_position_1'].fillna(0)
test['player_position_2']=test['player_position_2'].fillna(0)
test['player_height']=test['player_height'].fillna(test['player_height'].median())
test['player_weight']=test['player_weight'].fillna(test['player_weight'].median())
test['team']=test['team'].fillna(test['team'].value_counts()[0])
test['competitionId']=test['competitionId'].fillna(test['competitionId'].mode()[0])

In [8]:
train.isnull().sum()

row_id                               0
scout_id                             0
rating_num                           0
winner                               0
team                                 0
                                  ...
team2_defensive_derived_var_15    1427
team2_offensive_derived_var_16    1427
team2_defensive_derived_var_17    1427
team2_offensive_derived_var_18    1427
team2_offensive_derived_var_19    1427
Length: 800, dtype: int64

In [9]:
test.isnull().sum()

row_id                              0
scout_id                            0
winner                              0
team                                0
competitionId                       0
                                 ...
team2_defensive_derived_var_15    416
team2_offensive_derived_var_16    416
team2_defensive_derived_var_17    416
team2_offensive_derived_var_18    416
team2_offensive_derived_var_19    416
Length: 799, dtype: int64

In [12]:
train.describe()

,row_id,scout_id,rating_num,competitionId,player_position_1,player_position_2,player_height,player_weight,player_general_var_0,player_general_var_1,...,team2_defensive_derived_var_10,team2_offensive_derived_var_11,team2_offensive_derived_var_12,team2_offensive_derived_var_13,team2_offensive_derived_var_14,team2_defensive_derived_var_15,team2_offensive_derived_var_16,team2_defensive_derived_var_17,team2_offensive_derived_var_18,team2_offensive_derived_var_19
count,20453.000000,20453.000000,20453.000000,20453.000000,20453.000000,20453.000000,20453.000000,20453.000000,20453.000000,20453.000000,...,19026.000000,20332.000000,19019.000000,19021.000000,19026.000000,19026.000000,19026.000000,19026.000000,19026.000000,19026.000000
mean,14257.557033,10.023566,6.887303,7.311837,7.581577,7.983230,0.496926,0.455470,0.029717,0.003276,...,0.350022,0.179766,0.253738,0.582760,0.480930,0.497442,0.113251,0.424523,0.420103,0.333038
std,8353.543104,5.712044,1.852367,2.345699,5.071208,4.927983,0.160761,0.140841,0.082089,0.057142,...,0.140589,0.059541,0.138928,0.150763,0.163294,0.135420,0.061303,0.098739,0.121958,0.143902
min,1.000000,1.000000,0.000000,4.000000,0.000000,0.000000,0.024390,0.040000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.046945,0.000000,0.044144,0.000000,0.000000
25%,7048.000000,3.000000,6.000000,5.000000,3.000000,3.000000,0.390244,0.340000,0.000000,0.000000,...,0.246247,0.158557,0.153925,0.485600,0.365868,0.410089,0.068929,0.357223,0.333557,0.235558
50%,14093.000000,12.000000,6.500000,7.000000,7.000000,8.000000,0.512195,0.440000,0.000000,0.000000,...,0.339490,0.184254,0.239381,0.592093,0.479270,0.499538,0.102904,0.421710,0.420148,0.320256
75%,21381.000000,15.000000,8.000000,9.000000,11.000000,11.000000,0.609756,0.540000,0.000000,0.000000,...,0.431876,0.215570,0.338749,0.691803,0.596090,0.594952,0.149055,0.489914,0.507056,0.425171
max,29227.000000,26.000000,10.000000,15.000000,23.000000,23.000000,0.975610,1.000000,1.000000,1.000000,...,0.962835,1.000000,1.000000,1.000000,0.989602,0.977524,1.000000,1.000000,1.000000,1.000000

In [24]:
train=train.fillna(0)
test=test.fillna(0)

In [28]:
test1=test.drop(columns=train.columns[train.eq(0).mean()>0.8])
train1=train.drop(columns=train.columns[train.eq(0).mean()>0.8])

In [29]:
train1.shape

(20453, 581)

In [30]:
test1.shape

(8774, 580)

In [31]:
winner = {"winner": {"winner": 3, "loser": 1, "draw":2}}
train1.replace(winner , inplace = True)

In [32]:
team = {"team": {"team1": 1, "team2": 2}}
train1.replace(team , inplace = True)

In [33]:
test1.replace(winner , inplace = True)
test1.replace(team , inplace = True)

In [34]:
train1=train1.drop(['row_id','rating_num'],axis=1)

In [35]:
test1=test1.drop(['row_id'],axis=1)

In [36]:
from sklearn.model_selection import train_test_split

In [37]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(train1, y, test_size=0.3, random_state=32)

In [38]:
import xgboost as xgb
from sklearn.metrics import r2_score

C:\python\lib\site-packages\xgboost\compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index

In [43]:
lambda_values = [1, 10,0.1,0.001]

In [127]:
xgb_reg = xgb.XGBRegressor(max_depth=5, n_estimators=900, n_jobs=2,
                           objective='reg:squarederror', booster='gbtree',
                           random_state=42, learning_rate=0.05, reg_lambda=1)


xgb_reg.fit(X_train1, y_train1)

y_pred = xgb_reg.predict(X_test1)
y_true = y_test1


R_squared = r2_score(y_true, y_pred)

print("lambda = ", val)
print("R squared: ", np.round(R_squared, 2))

C:\python\lib\site-packages\xgboost\data.py:262: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

lambda =  0.001
R squared:  0.36

In [133]:
pred_test = xgb_reg.predict(test1)

In [134]:
submission['rating_num']=pred_test

In [135]:
submission.head()

   row_id  rating_num
0   14785    7.422023
1   15125    5.626236
2   13095    6.017270
3    6079    6.144081
4   16584    6.390500

In [136]:
submission.to_csv('Desktop/Analytics_Vidhya/football_hackathon/ss1_xgb12.csv',index=False)